version: '3'
services:
    rabbitmq:
        image: 'rabbitmq:3-management'
        hostname: 'rabbitmq'
        # expose:
        #   - '5672'
        ports:
          - '25672:5672'
          - '35672:15672'
          